#1
SELECT * 
FROM CUSTOMERS
WHERE ID NOT IN (SELECT DISTINCT CUSTOMERID FROM ORDERS);

#2
SELECT *
FROM CUSTOMERS
WHERE ID IN (SELECT DISTINCT CUSTOMERID FROM ORDERS WHERE TOTALAMOUNT = (SELECT MAX(TOTALAMOUNT) FROM ORDERS));


#3
SELECT *
FROM PRODUCTS
WHERE ID NOT IN (SELECT PRODUCTID FROM ORDERITEMS )

